.circleci/config.yml, README.md
=> feat: adding codecov

.github/CONTRIBUTING.md, .pre-commit-config.yaml, README.md, requirements.txt, src/algorithms/lstm_classifier/lstm_classifier.py, tests/sanity.py
=> feat: adding pre-commit

tests/algorithms/lstm_classifier/lstm_classifier_test.py
=> fix: adding test cases

app/sample-mint-config.json, fawkes/app_config/app_config.py, fawkes/constants.py, fawkes/fetch/comma_separated_values.py, fawkes/fetch/fetch.py, fawkes/fetch/remote.py, fawkes/parse/parse.py, fawkes/review/review.py
=> fix: adding the remote-file to fetch and json-lines to parse

.circleci/config.yml, .gitignore, README.md, fawkes/utils/utils.py, requirements.txt
=> fix: package updates

fawkes/algorithms/categorisation/lstm/trainer.py, fawkes/algorithms/categorisation/text_match/categoriser.py, fawkes/algorithms/sentiment/sentiment.py
=> fix: making the nltk installation as silent

.gitignore, fawkes/app_config/app-config-schema.json, fawkes/configs/app_config.py, fawkes/constants/constants.py
PR checklist:
Fixes #19 
- [#19 ] Github Issue associated with branch.
- [yes] PR branch is up-to-date with latest master branch.
=> Added App Config json schema validation

fawkes/datastore/elasticsearch.py
=> fix: adding some spaces

.gitignore, app/sample-mint-config.json, data/parsed_data/sample-mint/parsed-user-feedback.json, data/processed_data/sample-mint/processed-user-feedback.json, fawkes/configs/app-config-schema.json, fawkes/configs/app_config.py, fawkes/constants/constants.py, fawkes/fetch/appstore.py, fawkes/fetch/playstore.py, fawkes/parse/parse.py, fawkes/review/review.py, tests/sanity.py
=> fix: adding user_id and some bug fixes

app/fawkes-config.json, fawkes/utils/utils.py, requirements.txt
=> fix: remove the spacy requirement

requirements.txt
=> fix: adding numpy to requirements

fawkes/slackbot/slackbot.py
=> fix: fixing the ratings issue

fawkes/algorithms/algo.py, fawkes/cli/cli.py, fawkes/cli/fawkes_actions.py, fawkes/constants/logs.py, fawkes/fetch/appstore.py, fawkes/fetch/fetch.py, fawkes/fetch/playstore.py, fawkes/parse/parse.py, fawkes/slackbot/slackbot.py
=> fix: adding logging to fawkes

fawkes/utils/filter_utils.py
=> fix: filtering reviews which are in future time

app/sample-mint-config.json, fawkes/configs/app-config-schema.json, fawkes/configs/app_config.py, fawkes/fetch/fetch.py, fawkes/fetch/splunk.py, requirements.txt
PR checklist:
Resolves #10
- [#10  ] Github Issue associated with branch.
- [ Yes ] PR branch is up-to-date with latest master branch.
=> Support Splunk as Datasource

app/sample-mint-config.json, data/parsed_data/sample-mint/parsed-user-feedback.json, data/processed_data/sample-mint/processed-user-feedback.json, fawkes/parse/parse.py, tests/sanity.py
=> fix: minor bug fixes

.gitignore, app/sample-mint-config.json, fawkes/algorithms/algo.py, fawkes/configs/app_config.py, fawkes/datastore/elasticsearch.py, fawkes/parse/parse.py, fawkes/slackbot/slackbot.py, scripts/install-elastic.sh
=> fix: some more changes

fawkes/slackbot/slackbot.py
=> fix: adding user identifier in slackbot

.circleci/config.yml, app/sample-mint-config.json, data/parsed_data/sample-mint/parsed-user-feedback.json, data/processed_data/sample-mint/processed-user-feedback.json, fawkes/configs/app_config.py, fawkes/configs/schemas/app-config-schema.json, fawkes/constants/constants.py, fawkes/parse/parse.py, fawkes/review/review.py, tests/sanity.py
=> fix: adding rating normalisation

data/parsed_data/sample-mint/parsed-user-feedback.json, data/processed_data/sample-mint/processed-user-feedback.json, fawkes/constants/logs.py, fawkes/review/review.py, fawkes/utils/utils.py, tests/sanity.py
=> fix: some elastic search related things

fawkes/cli/cli.py, fawkes/datastore/elasticsearch.py
=> fix: adding the action as the separate function

app/sample-mint-config.json, fawkes/configs/app_config.py, fawkes/slackbot/slackbot.py
=> fix: adding custom slack channle notification for each channel

data/processed_data/sample-mint/processed-user-feedback.json, fawkes/algorithms/algo.py, fawkes/algorithms/categorisation/lstm/trainer.py, fawkes/algorithms/categorisation/text_match/categoriser.py, fawkes/algorithms/categorisation/text_match/trainer.py, fawkes/algorithms/sentiment/sentiment.py, fawkes/configs/app_config.py, fawkes/constants/logs.py, fawkes/datastore/elasticsearch.py, fawkes/datastore/lifetime_rating.py, fawkes/email_summary/email_summary_detailed.py, fawkes/email_summary/send_email.py, fawkes/fetch/appstore.py, fawkes/fetch/playstore.py, fawkes/fetch/salesforce.py, fawkes/fetch/tweets.py, fawkes/parse/parse.py, fawkes/review/review.py, fawkes/slackbot/slackbot.py, fawkes/utils/utils.py
=> fix: add more logging to the exception

fawkes/algorithms/categorisation/text_match/categoriser.py
=> fix: adding the nltk download
